apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: camel-ai-kafka
spec:
  kafka:
    config:
      default.replication.factor: 3
      inter.broker.protocol.version: "3.6"
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - name: tls
      port: 9093
      tls: true
      type: internal
    replicas: 3
    storage:
      deleteClaim: true
      size: 10Gi
      type: persistent-claim
    version: 3.6.0
  zookeeper:
    replicas: 3
    storage:
      class: 5Gi
      type: persistent-claim