apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/megacamelus/qdrant-operator//config/default

images:
- digest: sha256:e9ef3840524b4d24409108e79effc808b914439f72096b96703b878b052618fc
  name: quay.io/megacamelus/qdrant-operator
