apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/megacamelus/qdrant-operator//config/default

images:
- digest: sha256:218d5cae9da56d3734ee6223dcc5005ac4d7a6ca38e9df50469677c6d547e86c
  name: quay.io/megacamelus/qdrant-operator
