apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camel-ai-qdrant
  namespace: openshift-gitops
spec:
  destination:
    namespace: qdrant-system
    server: 'https://kubernetes.default.svc'
  source:
    path: etc/kubernetes/infra/qdrant
    repoURL: 'https://github.com/megacamelus/camel-assistant-manifests'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
