apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camel-ai-infra
  namespace: openshift-gitops
spec:
  project: default
  destination:
    namespace: camel-ai
    server: 'https://kubernetes.default.svc'
  source:
    path: etc/kubernetes/infra
    repoURL: 'https://github.com/megacamelus/camel-assistant-manifests'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
