apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camel-ai-qdrant
  namespace: camel-ai
spec:
  destination:
    name: ''
    namespace: camel-ai
    server: 'https://kubernetes.default.svc'
  source:
    path: etc/kubernetes/base/qdrant
    repoURL: 'https://github.com/megacamelus/camel-assistant-manifests'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
