---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: assistant-backend
  name: assistant-backend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: assistant-backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: assistant-backend
  name: assistant-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: assistant-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: assistant-backend
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/megacamelus/assistant-backend:latest
          imagePullPolicy: Always
          name: assistant-backend
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
