apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: camel-ai-ingestion-siknk
  annotations:
      trait.camel.apache.org/container.image: 'quay.io/megacamelus/assistant-ingestion-sink:latest'
      trait.camel.apache.org/jvm.enabled: 'false'
      trait.camel.apache.org/kamelets.enabled: 'false'
      trait.camel.apache.org/dependencies.enabled: 'false'
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta2
      name: camel-ai-ingestion
    properties:
      brokers: 'camel-ai-kafka-kafka-bootstrap.camel-ai.svc:9092'
  steps:
    - ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1
        name: langchain-embeddings-action
      properties:
        embeddingId: 'camel-ai-ingestion-siknk'
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: qdrant-upsert-sink
    properties:
      collection: 'cai'
      qdrantHost: 'camel-ai'
      qdrantPort: '6334'