apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- qdrant.yaml
- ingestion.yaml

namespace: camel-ai
images:
- digest: sha256:80bad7f55377a0eab2855371bc8792e82147469aae35e2f1839dbfe7afa71970
  name: quay.io/megacamelus/assistant-backend
- digest: sha256:cbab404b1159fcd88f6d0b77fedd699f51ff080a473cd27ae5f5ec58132227b9
  name: quay.io/megacamelus/assistant-ui-vaadin
