apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- qdrant.yaml
- ingestion-sink-topic.yaml
- ingestion-sink-pipe.yaml

namespace: camel-ai
images:
- digest: sha256:0cfc5e3eb4995a24be846081e911ad7ec33b085a5c3e9dc9d45fa39bbc3c6da3
  name: quay.io/megacamelus/assistant-backend
- digest: sha256:b02e9549019fc25cbcaf18f42615f6b43c2e50d28d7c037c7783b75425d71406
  name: quay.io/megacamelus/assistant-ui-vaadin
