apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- qdrant.yaml

namespace: camel-ai
images:
- digest: sha256:1d6eefe782f104f8de52aa5020659665b4b995d83d9c8bf7648098be0e003118
  name: quay.io/megacamelus/assistant-backend
- digest: sha256:c391dce9099eca07a8339ff6585751d3e1f3bcb49b8a07532571ade6873d6bad
  name: quay.io/megacamelus/assistant-ui-vaadin
