apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- qdrant.yaml
- ingestion-sink-topic.yaml
- ingestion-sink-pipe.yaml

namespace: camel-ai
images:
- digest: sha256:5c31c7dbef8000f9fcffd496f4fcaa8b1f0e711e535b3e2b84f0f935f8ccdb7c
  name: quay.io/megacamelus/assistant-backend
- digest: sha256:6a29f0dafc043825b0e6e76dedb670f566988bf569d1ceb7e30a6a56893bfc88
  name: quay.io/megacamelus/assistant-ui-vaadin
