apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- qdrant.yaml
namespace: camel-ai
images:
- digest: sha256:ca799cd97c719b03c7fc88d0c4c0fbdc69d9e9fee43b8a25f196b081b644d9f8
  name: quay.io/megacamelus/assistant-backend
