apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- qdrant.yaml
- ingestion-sink-topic.yaml
- ingestion-sink-pipe.yaml

namespace: camel-ai
images:
- digest: sha256:9ec533242af57ce2dbeb46b249e644f5bb0c4e61c32c8bb11520da8b82ecb38e
  name: quay.io/megacamelus/assistant-backend
- digest: sha256:72bc87bfe7b53e2dda943f148c669290b64470a96e2c33c7ef03267e73df0bc4
  name: quay.io/megacamelus/assistant-ui-vaadin
