apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- qdrant.yaml

namespace: camel-ai
images:
- digest: sha256:235bc3adf891773f60a52f6763aa3bf864ef976c3f5560d63bb5f768d55153ff
  name: quay.io/megacamelus/assistant-backend
- digest: sha256:c8463e2f18f77bc2640de5026d176e5505ba9662e3fb4b5cb58930f5fd387f83
  name: quay.io/megacamelus/assistant-ui-vaadin
