apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- qdrant.yaml

namespace: camel-ai
images:
- digest: sha256:0ca2bc0ced972891138951a207d59f84ec5dc2a29760bdcc6008aabe8d66442e
  name: quay.io/megacamelus/assistant-backend
- digest: sha256:00da8e73def87fd00db7d7509ea8105e0acc428807b2ee7c7c0cf1aaa5ee3a23
  name: quay.io/megacamelus/assistant-ui-vaadin
