apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- qdrant.yaml

namespace: camel-ai
images:
- digest: sha256:654050959a03f12531f3301275fe58f78eb4e0f16545e8ebacccbfe1500a8544
  name: quay.io/megacamelus/assistant-backend
- digest: sha256:34d00ee60ac0a2b01c5a243deeb983b2d52e209e5e27373de5ef0cdd836c0c81
  name: quay.io/megacamelus/assistant-ui-vaadin
