apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- qdrant.yaml
- ingestion-sink-topic.yaml
- ingestion-sink-pipe.yaml

namespace: camel-ai
images:
- digest: sha256:6e082b1a015a9dc300ac4e6e6fa0bbec39f161e20cae5ccaedb39d2106cfd156
  name: quay.io/megacamelus/assistant-backend
- digest: sha256:ad6ba5d5a8faa04b039dd7d6f4d4a559ffd449bceb3b2513b0eb40336fc1e8d0
  name: quay.io/megacamelus/assistant-ui-vaadin
