apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- qdrant.yaml
namespace: camel-ai
images:
- digest: sha256:4ed32a301f4d45cf5caa23911016133952a2312f572292538e51306ba8eb4902
  name: quay.io/megacamelus/assistant-backend
