apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- qdrant.yaml
- ingestion-sink-topic.yaml
- ingestion-sink-pipe.yaml

namespace: camel-ai
images:
- digest: sha256:a8612f9007ef14f1286b0bf0710d5f3a61bbd1b05e3a78d4ae16483b3913963c
  name: quay.io/megacamelus/assistant-backend
- digest: sha256:b79f057b55ce7ad40c9685b7f7ed6253172535b9ca2b339d87d71332f2d7780a
  name: quay.io/megacamelus/assistant-ui-vaadin
