apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- qdrant.yaml
- ingestion-sink-topic.yaml
- ingestion-sink-pipe.yaml

namespace: camel-ai
images:
- digest: sha256:e6b73fb9b01e497af7404fead959a823aa9d967026451bd5b4ef05d8f344d360
  name: quay.io/megacamelus/assistant-backend
- digest: sha256:24110f7a9995297cb618e1d6020758be46254109e9d75fc41fa752d03b793e76
  name: quay.io/megacamelus/assistant-ui-vaadin
