apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- qdrant.yaml

namespace: camel-ai
images:
- digest: sha256:67f4c4a4157cdbbe5c5916e7dede2cf8d39c7f0b211562433cee77efe4954a67
  name: quay.io/megacamelus/assistant-backend
- digest: sha256:676c045bbdb44c4355e7afc697a7820bb80c088350412ea2d688a8e2c3ecfc0a
  name: quay.io/megacamelus/assistant-ui-vaadin
