apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- qdrant.yaml
namespace: camel-ai
images:
- digest: sha256:c7892a18f354a016003c88390215816195a497c4cc9a69f1d35b5c655ff626d1
  name: quay.io/megacamelus/assistant-backend
