apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- frontend.yaml
- qdrant.yaml

namespace: camel-ai
images:
- digest: sha256:8d76b495c3014a2be7902d48c10f61247985ae2bf5448ee75f133b2294589089
  name: quay.io/megacamelus/assistant-backend
- digest: sha256:65e79d12530216b862af47316be4ef8c2c2380b6d9d38c872e33b63c3ad6e66b
  name: quay.io/megacamelus/assistant-ui-vaadin
