apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend.yaml
- qdrant.yaml
namespace: camel-ai
images:
- digest: sha256:53cb1fdb218715419da055859604eb7d133d4b7b5919a2592cb1daef80a83645
  name: quay.io/megacamelus/assistant-backend
- digest: sha256:78a87f4c19c0bd416aecd3e25bb44f6c70b3b0a914cf1b2d4a6658134239f845
  name: quay.io/megacamelus/assistant-ui-vaadin
